CardjamFlipCards.NULL_REPORT_LUCK_UP = Isaac.GetNullItemIdByName("report luck up")

CardjamFlipCards.COLLECTIBLE_DOUBLE_SIDED_CARD = Isaac.GetItemIdByName("Double-Sided Card")

CardjamFlipCards.CARD_REPORT = Isaac.GetCardIdByName("Report")
CardjamFlipCards.CARD_SCRATCH = Isaac.GetCardIdByName("Scratch")
CardjamFlipCards.CARD_CHARM = Isaac.GetCardIdByName("Charm")
CardjamFlipCards.CARD_BOARD = Isaac.GetCardIdByName("Board")

CardjamFlipCards.CARD_REPORT_ALT = Isaac.GetCardIdByName("Report (alt)")
CardjamFlipCards.CARD_SCRATCH_ALT = Isaac.GetCardIdByName("Scratch (alt)")
CardjamFlipCards.CARD_CHARM_ALT = Isaac.GetCardIdByName("Charm (alt)")
CardjamFlipCards.CARD_BOARD_ALT = Isaac.GetCardIdByName("Board (alt)")

CardjamFlipCards.TEAR_SCRATCH_ALT = Isaac.GetEntityVariantByName("Scratch (alt) Tear")

CardjamFlipCards.SFX_JACKPOT = Isaac.GetSoundIdByName("Jackpot (CardJam)")
CardjamFlipCards.SFX_CHALK = Isaac.GetSoundIdByName("Chalk (CardJam)")
CardjamFlipCards.SFX_ERROR = Isaac.GetSoundIdByName("Error (CardJam)")
CardjamFlipCards.SFX_VOICE_REPORT_1 = Isaac.GetSoundIdByName("Voice Report 1 (CardJam)")
CardjamFlipCards.SFX_VOICE_REPORT_2 = Isaac.GetSoundIdByName("Voice Report 2 (CardJam)")
CardjamFlipCards.SFX_VOICE_SCRATCH_1 = Isaac.GetSoundIdByName("Voice Scratch 1 (CardJam)")
CardjamFlipCards.SFX_VOICE_SCRATCH_2 = Isaac.GetSoundIdByName("Voice Scratch 2 (CardJam)")
CardjamFlipCards.SFX_VOICE_CHARM_1 = Isaac.GetSoundIdByName("Voice Charm 1 (CardJam)")
CardjamFlipCards.SFX_VOICE_CHARM_2 = Isaac.GetSoundIdByName("Voice Charm 2 (CardJam)")
CardjamFlipCards.SFX_VOICE_BOARD_1 = Isaac.GetSoundIdByName("Voice Board 1 (CardJam)")
CardjamFlipCards.SFX_VOICE_BOARD_2 = Isaac.GetSoundIdByName("Voice Board 2 (CardJam)")

CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_JACKPOT)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_CHALK)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_ERROR)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_REPORT_1)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_REPORT_2)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_SCRATCH_1)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_SCRATCH_2)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_CHARM_1)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_CHARM_2)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_BOARD_1)
CardjamFlipCards.SFX:Preload(CardjamFlipCards.SFX_VOICE_BOARD_2)